/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAviatorRouteImport } from './routes/_authenticated/aviator'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBotsRouteImport } from './routes/_authenticated/bots'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExchangesRouteImport } from './routes/_authenticated/exchanges'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as ApiAviatorRoundRouteImport } from './routes/api/aviator-round'
import { Route as ApiCryptoChargeRouteImport } from './routes/api/crypto-charge'
import { Route as ApiCryptoMinRouteImport } from './routes/api/crypto-min'
import { Route as ApiCryptoStatusRouteImport } from './routes/api/crypto-status'
import { Route as AuthenticatedBotsBotIdRouteImport } from './routes/_authenticated/bots.$botId'
import { Route as ApiPublicBotTickRouteImport } from './routes/api/public/bot-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAviatorRoute = AuthenticatedAviatorRouteImport.update({
  id: '/aviator',
  path: '/aviator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotsRoute = AuthenticatedBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExchangesRoute = AuthenticatedExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAviatorRoundRoute = ApiAviatorRoundRouteImport.update({
  id: '/api/aviator-round',
  path: '/api/aviator-round',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCryptoChargeRoute = ApiCryptoChargeRouteImport.update({
  id: '/api/crypto-charge',
  path: '/api/crypto-charge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCryptoMinRoute = ApiCryptoMinRouteImport.update({
  id: '/api/crypto-min',
  path: '/api/crypto-min',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCryptoStatusRoute = ApiCryptoStatusRouteImport.update({
  id: '/api/crypto-status',
  path: '/api/crypto-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBotsBotIdRoute = AuthenticatedBotsBotIdRouteImport.update({
  id: '/$botId',
  path: '/$botId',
  getParentRoute: () => AuthenticatedBotsRoute,
} as any)
const ApiPublicBotTickRoute = ApiPublicBotTickRouteImport.update({
  id: '/api/public/bot-tick',
  path: '/api/public/bot-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aviator': typeof AuthenticatedAviatorRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/bots': typeof AuthenticatedBotsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exchanges': typeof AuthenticatedExchangesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/aviator-round': typeof ApiAviatorRoundRoute
  '/api/crypto-charge': typeof ApiCryptoChargeRoute
  '/api/crypto-min': typeof ApiCryptoMinRoute
  '/api/crypto-status': typeof ApiCryptoStatusRoute
  '/bots/$botId': typeof AuthenticatedBotsBotIdRoute
  '/api/public/bot-tick': typeof ApiPublicBotTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aviator': typeof AuthenticatedAviatorRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/bots': typeof AuthenticatedBotsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exchanges': typeof AuthenticatedExchangesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/aviator-round': typeof ApiAviatorRoundRoute
  '/api/crypto-charge': typeof ApiCryptoChargeRoute
  '/api/crypto-min': typeof ApiCryptoMinRoute
  '/api/crypto-status': typeof ApiCryptoStatusRoute
  '/bots/$botId': typeof AuthenticatedBotsBotIdRoute
  '/api/public/bot-tick': typeof ApiPublicBotTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/aviator': typeof AuthenticatedAviatorRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/bots': typeof AuthenticatedBotsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exchanges': typeof AuthenticatedExchangesRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/aviator-round': typeof ApiAviatorRoundRoute
  '/api/crypto-charge': typeof ApiCryptoChargeRoute
  '/api/crypto-min': typeof ApiCryptoMinRoute
  '/api/crypto-status': typeof ApiCryptoStatusRoute
  '/_authenticated/bots/$botId': typeof AuthenticatedBotsBotIdRoute
  '/api/public/bot-tick': typeof ApiPublicBotTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/aviator'
    | '/billing'
    | '/bots'
    | '/dashboard'
    | '/exchanges'
    | '/wallet'
    | '/api/aviator-round'
    | '/api/crypto-charge'
    | '/api/crypto-min'
    | '/api/crypto-status'
    | '/bots/$botId'
    | '/api/public/bot-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/aviator'
    | '/billing'
    | '/bots'
    | '/dashboard'
    | '/exchanges'
    | '/wallet'
    | '/api/aviator-round'
    | '/api/crypto-charge'
    | '/api/crypto-min'
    | '/api/crypto-status'
    | '/bots/$botId'
    | '/api/public/bot-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/aviator'
    | '/_authenticated/billing'
    | '/_authenticated/bots'
    | '/_authenticated/dashboard'
    | '/_authenticated/exchanges'
    | '/_authenticated/wallet'
    | '/api/aviator-round'
    | '/api/crypto-charge'
    | '/api/crypto-min'
    | '/api/crypto-status'
    | '/_authenticated/bots/$botId'
    | '/api/public/bot-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAviatorRoundRoute: typeof ApiAviatorRoundRoute
  ApiCryptoChargeRoute: typeof ApiCryptoChargeRoute
  ApiCryptoMinRoute: typeof ApiCryptoMinRoute
  ApiCryptoStatusRoute: typeof ApiCryptoStatusRoute
  ApiPublicBotTickRoute: typeof ApiPublicBotTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aviator': {
      id: '/_authenticated/aviator'
      path: '/aviator'
      fullPath: '/aviator'
      preLoaderRoute: typeof AuthenticatedAviatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots': {
      id: '/_authenticated/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof AuthenticatedBotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exchanges': {
      id: '/_authenticated/exchanges'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof AuthenticatedExchangesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/aviator-round': {
      id: '/api/aviator-round'
      path: '/api/aviator-round'
      fullPath: '/api/aviator-round'
      preLoaderRoute: typeof ApiAviatorRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crypto-charge': {
      id: '/api/crypto-charge'
      path: '/api/crypto-charge'
      fullPath: '/api/crypto-charge'
      preLoaderRoute: typeof ApiCryptoChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crypto-min': {
      id: '/api/crypto-min'
      path: '/api/crypto-min'
      fullPath: '/api/crypto-min'
      preLoaderRoute: typeof ApiCryptoMinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crypto-status': {
      id: '/api/crypto-status'
      path: '/api/crypto-status'
      fullPath: '/api/crypto-status'
      preLoaderRoute: typeof ApiCryptoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bots/$botId': {
      id: '/_authenticated/bots/$botId'
      path: '/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof AuthenticatedBotsBotIdRouteImport
      parentRoute: typeof AuthenticatedBotsRoute
    }
    '/api/public/bot-tick': {
      id: '/api/public/bot-tick'
      path: '/api/public/bot-tick'
      fullPath: '/api/public/bot-tick'
      preLoaderRoute: typeof ApiPublicBotTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBotsRouteChildren {
  AuthenticatedBotsBotIdRoute: typeof AuthenticatedBotsBotIdRoute
}

const AuthenticatedBotsRouteChildren: AuthenticatedBotsRouteChildren = {
  AuthenticatedBotsBotIdRoute: AuthenticatedBotsBotIdRoute,
}

const AuthenticatedBotsRouteWithChildren =
  AuthenticatedBotsRoute._addFileChildren(AuthenticatedBotsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAviatorRoute: typeof AuthenticatedAviatorRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBotsRoute: typeof AuthenticatedBotsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExchangesRoute: typeof AuthenticatedExchangesRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAviatorRoute: AuthenticatedAviatorRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBotsRoute: AuthenticatedBotsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExchangesRoute: AuthenticatedExchangesRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAviatorRoundRoute: ApiAviatorRoundRoute,
  ApiCryptoChargeRoute: ApiCryptoChargeRoute,
  ApiCryptoMinRoute: ApiCryptoMinRoute,
  ApiCryptoStatusRoute: ApiCryptoStatusRoute,
  ApiPublicBotTickRoute: ApiPublicBotTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
